version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      NAME: "rabbitmq"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend

  mrb-api:
    build:
      context: ../src/MRB
      dockerfile: MRB.Api/Dockerfile
    container_name: mrb-api
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"  # Mapeando a porta externa 5000 para a interna 8080 (do EXPOSE)
    networks:
      - backend

volumes:
  rabbitmq_data:

networks:
  backend:
    driver: bridge